name: Investment Job

on:
  workflow_call:
  workflow_dispatch:

env:
  max_workers: 5
  sheet: 'Investment'

jobs:
  worker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: 
        chunk: [0, 1, 2, 3, 4]
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'


      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Install Playwright Browsers and System Dependencies
        run: |
          playwright install chromium --with-deps

      - name: Cleanup CSV
        run: rm -rf csv/*_${{env.sheet}}.csv

      - name: Run Scraper Chunk
        run: python main.py --id ${{ matrix.chunk }} --max ${{env.max_workers}} --sheet ${{env.sheet}}

      - name: Upload Partial Data
        uses: actions/upload-artifact@v4
        with:
          name: results-${{env.sheet}}-csv-${{matrix.chunk}}
          path: csv/ii_${{matrix.chunk}}_${{env.sheet}}.csv
          if-no-files-found: error
 
  merge-results:
    needs: worker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: csv
          pattern: results-${{env.sheet}}-csv-*
          merge-multiple: true

      # 1. Run merge code
      - name: Merge and Commit
        run: python main.py --merge --sheet ${{env.sheet}}

      - name: Upload Spreadsheet
        uses: actions/upload-artifact@v4
        with:
          name: ii-${{env.sheet}}
          path: spreadsheet
          if-no-files-found: error

      # 2. Pull immediately before committing with autostash enabled

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "Updated: spreadsheet"
          branch: main