name: Orchestrator
on:
  workflow_dispatch:
    #schedule:
    #- cron: "38 2 1 */3 *"
    #- cron: "38 11 3 * *"


env:
  IDLE_TIME: 60

jobs:
  run-spreadsheet-workflow:
    uses: ./.github/workflows/spreadsheet.yml

  wait-after-spreadsheet:
    needs: run-spreadsheet-workflow
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: sleep 10

  run-urls-workflow:
    needs: wait-after-spreadsheet
    uses: ./.github/workflows/URLs.yml

  wait-after-urls:
    needs: run-urls-workflow
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: sleep ${{ env.IDLE_TIME }}

  run-investment-workflow:
    needs: wait-after-urls
    uses: ./.github/workflows/Investment.yml
  
  wait-after-investment:
    needs: run-investment-workflow
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: sleep ${{ env.IDLE_TIME }}

  run-etf-workflow:
    needs: wait-after-investment
    if: always()
    uses: ./.github/workflows/ETF.yml

  wait-after-etf:
    needs: run-etf-workflow
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: sleep ${{ env.IDLE_TIME }}

  run-mf-workflow:
    needs: wait-after-etf
    uses: ./.github/workflows/MF.yml
  
  run-email-workflow:
    needs: run-mf-workflow
    uses: ./.github/workflows/Email.yml
    secrets: inherit
